### ISSUE TITLE
Permissions needed

### ISSUE THREAD

**Issue by mikaellofgren** [red5coder/Jamf-Framework-Redeploy#2]
Thanks for this little app, I had a small permission issue, that was needed, if I wanted a bare minimum account on Jamf
what also is needed:
Jamf Pro Server Setting - "Check-In" - Read (is needed)

This is what Jamf Support told me and I confirmed it working, maybe you want to update the Read me.

**Comment by red5coder** [comment]
Thank you ,l will update that now.

Very much appreciated
