### ISSUE TITLE
Password "Save Password" not working

### ISSUE THREAD

**Issue by mvught** [red5coder/Jamf-Framework-Redeploy#3]
If you hit "save password" and check the box, reopen "Jamf-Framework-Redeploy" the password is gone.
Thanks for app great work use it daily!

**Comment by red5coder** [comment]
Hi there

Thanks for the feedback. I have just posted v1.0.1 which should fix the keychain issue. Let me know if you see any other issues.

**Comment by mvught** [comment]
Still no luck, its stays unfilled and greyed out.
